// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbmnuwxnddjvupvgkmsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibW51d3huZGRqdnVwdmdrbXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzMjM0MjAsImV4cCI6MjA5OTg5OTQyMH0.8y2ZfxG5VzV42zMBb30u2ox1qN23xUD5DRYsJlzpVBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const safeStorage = {
  getItem: (key: string) => {
    try {
      return globalThis.localStorage?.getItem(key) ?? null;
    } catch (error) {
      console.error('Failed to read from localStorage:', error);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      globalThis.localStorage?.setItem(key, value);
    } catch (error) {
      console.error('Failed to write to localStorage:', error);
    }
  },
  removeItem: (key: string) => {
    try {
      globalThis.localStorage?.removeItem(key);
    } catch (error) {
      console.error('Failed to remove from localStorage:', error);
    }
  },
};

// Supabase client instance
if (typeof window !== 'undefined') {
  const currentProjectRef = 'pbmnuwxnddjvupvgkmsw';
  Object.keys(localStorage).forEach(key => {
    if (key.startsWith('sb-') && !key.includes(currentProjectRef)) {
      localStorage.removeItem(key);
    }
  });
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      apikey: SUPABASE_PUBLISHABLE_KEY,
    },
  },
});
